#!/bin/bash
echo "A: This script is sending this text to stdout"
echo "B: This script is sending this text to stdout" >>/dev/stdout
echo "C: This script is sending this text to stderr" >/dev/stderr
echo "D: This script is sending this text to stderr" >>/dev/stderr
echo "E: This script is sending this text to stderr" >>/dev/stderr
